# frozen_string_literal: true

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyBeaver'
  pod 'xray', path: '/Users/antonkononenko/Work/x-ray/apple/xray.podspec'
end
