# frozen_string_literal: true

# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'XrayLogger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyBeaver'

  target 'XrayLoggerTests' do
    # Pods for testing
  end
end
