# frozen_string_literal: true

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xray' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyBeaver'

  target 'xrayTests' do
    # Pods for testing
  end
end
